version: "3.8"

services:
  image-to-sketch:
    image: 150619449649.dkr.ecr.ap-south-1.amazonaws.com/image-to-sketch:latest

    container_name: image-to-sketch

    restart: unless-stopped

    ports:
      - "5000:5000"

    env_file:
      - .env

    volumes:
      - uploads-data:/app/static/uploads

volumes:
  uploads-data: