sonar.projectKey=image-to-sketch
sonar.projectName=Image-to-Sketch
sonar.projectVersion=1.0

sonar.sources=.
sonar.sourceEncoding=UTF-8

sonar.exclusions=\
venv/**,\
__pycache__/**,\
*.pyc,\
.git/**,\
trivy-report.html,\
trivy-report.txt

sonar.python.version=3