sonar.projectKey=image-to-sketch
sonar.projectName=Image-to-Sketch
sonar.projectVersion=1.0

sonar.sources=.
sonar.sourceEncoding=UTF-8

# Exclude unnecessary files
sonar.exclusions=venv/**,__pycache__/**,*.pyc,.git/**

# Python version
sonar.python.version=3