name: Image-to-Sketch CI/CD

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Display Runner Information
        run: |
          echo "===== GitHub Runner Information ====="
          echo "Current Directory:"
          pwd

          echo ""
          echo "Repository Files:"
          ls -la

          echo ""
          echo "Docker Version:"
          docker --version

          echo ""
          echo "Docker Compose Version:"
          docker compose version
